### ISSUE TITLE
open facility cluster 

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1495]
The facility clusters to not open on click/zoom.
![Screenshot from 2022-10-18 09-14-33](https://user-images.githubusercontent.com/38838/196419485-fdd6ca09-72e8-45cc-9e25-2b486a053429.png)
https://healthsites.io/map?country=India

**Comment by nixilla** [comment]
Error message:

```
cluster.534a14d0418a.js:249 Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at NewClass.<anonymous> (cluster.534a14d0418a.js:249:61)
    at NewClass.fireEvent (leaflet-src.c8aadb9ba5da.js:461:25)
    at NewClass._onMouseClick (leaflet-src.c8aadb9ba5da.js:3694:8)
    at HTMLDivElement.handler [as _leaflet_click31] (leaflet-src.c8aadb9ba5da.js:6380:14)
```
