### ISSUE TITLE
Instructions in README.md fail.

### ISSUE THREAD

**Issue by milovanderlinden** [healthsites/healthsites#853]
When running

```bash
python manage.py migrate
```
The process fails with:

```python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/data/Development/healthsites/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/data/Development/healthsites/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/data/Development/healthsites/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/data/Development/healthsites/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/data/Development/healthsites/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/data/Development/healthsites/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/data/Development/healthsites/django_project/core/settings/dev.py", line 1, in <module>
    from .project import *  # noqa
  File "/data/Development/healthsites/django_project/core/settings/project.py", line 12, in <module>
    from .contrib import *  # noqa
  File "/data/Development/healthsites/django_project/core/settings/contrib.py", line 134, in <module>
    BROKER_URL = 'amqp://guest:guest@%s:5672//' % os.environ['RABBITMQ_HOST']
  File "/data/Development/healthsites/venv/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'RABBITMQ_HOST'
```

**Comment by milovanderlinden** [comment]
I found out the instructions require two extra settings:
```
export RABBITMQ_HOST=localhost
export DJANGO_SETTINGS_MODULE=core.settings.test_${USER}
```
